// rtl8188efw.h
// Generated by decompiling rtl8188efw.bin
// using Reko decompiler version 0.11.4.0.

/*
// Equivalence classes ////////////
Eq_1: (struct "Globals")
	globals_t (in globals : (ptr16 (struct "Globals")))
Eq_2: (segment "Eq_2" (1D byte b001D) (157 byte b0157) (80EA bcu8 b80EA))
	T_2 (in __data : (ptr16 Eq_2))
Eq_7: (fn void ())
	T_7 (in fn4EF3 @ 0797 : ptr16)
Eq_23: (fn void ())
	T_23 (in fn4AC0 @ 07A7 : ptr16)
// Type Variables ////////////
globals_t: (in globals : (ptr16 (struct "Globals")))
  Class: Eq_1
  DataType: (ptr16 Eq_1)
  OrigDataType: (ptr16 (struct "Globals"))
T_2: (in __data : (ptr16 Eq_2))
  Class: Eq_2
  DataType: (ptr16 Eq_2)
  OrigDataType: (ptr16 (segment (1D T_6 t001D) (157 T_13 t0157) (80EA T_16 t80EA)))
T_3: (in 0<8> @ 077C : byte)
  Class: Eq_3
  DataType: byte
  OrigDataType: byte
T_4: (in 0x001D<p16> @ 077C : mp16)
  Class: Eq_4
  DataType: (memptr (ptr16 Eq_2) byte)
  OrigDataType: (memptr T_2 (struct (0 T_6 t0000)))
T_5: (in __data:0x001D<p16> @ 077C : segptr32)
  Class: Eq_5
  DataType: segptr32
  OrigDataType: segptr32
T_6: (in Mem8[__data:0x001D<p16>:byte] @ 077C : byte)
  Class: Eq_3
  DataType: byte
  OrigDataType: byte
T_7: (in fn4EF3 @ 0797 : ptr16)
  Class: Eq_7
  DataType: (ptr16 Eq_7)
  OrigDataType: (ptr16 (fn T_9 ()))
T_8: (in signature of fn4EF3 : void)
  Class: Eq_8
  DataType: Eq_8
  OrigDataType: 
T_9: (in fn4EF3() @ 0797 : void)
  Class: Eq_9
  DataType: void
  OrigDataType: void
T_10: (in 5<8> @ 079F : byte)
  Class: Eq_10
  DataType: byte
  OrigDataType: byte
T_11: (in 0x157<16> @ 079F : word16)
  Class: Eq_11
  DataType: (memptr (ptr16 Eq_2) byte)
  OrigDataType: (memptr T_2 (struct (0 T_13 t0000)))
T_12: (in __data:0x157<16> @ 079F : segptr32)
  Class: Eq_12
  DataType: segptr32
  OrigDataType: segptr32
T_13: (in Mem32[__data:0x157<16>:byte] @ 079F : byte)
  Class: Eq_10
  DataType: byte
  OrigDataType: byte
T_14: (in 0x80EA<16> @ 07A4 : word16)
  Class: Eq_14
  DataType: (memptr (ptr16 Eq_2) bcu8)
  OrigDataType: (memptr T_2 (struct (0 T_16 t0000)))
T_15: (in __data:0x80EA<16> @ 07A4 : segptr32)
  Class: Eq_15
  DataType: segptr32
  OrigDataType: segptr32
T_16: (in Mem32[__data:0x80EA<16>:byte] @ 07A4 : byte)
  Class: Eq_16
  DataType: bcu8
  OrigDataType: bcu8
T_17: (in 2<8> @ 07A4 : byte)
  Class: Eq_17
  DataType: byte
  OrigDataType: byte
T_18: (in __data->b80EA >> 2<8> @ 07A4 : byte)
  Class: Eq_18
  DataType: uint8
  OrigDataType: uint8
T_19: (in 1<8> @ 07A4 : byte)
  Class: Eq_19
  DataType: byte
  OrigDataType: byte
T_20: (in __data->b80EA >> 2<8> & 1<8> @ 07A4 : byte)
  Class: Eq_20
  DataType: byte
  OrigDataType: byte
T_21: (in 0<8> @ 07A4 : byte)
  Class: Eq_20
  DataType: byte
  OrigDataType: byte
T_22: (in (__data->b80EA >> 2<8> & 1<8>) != 0<8> @ 07A4 : bool)
  Class: Eq_22
  DataType: bool
  OrigDataType: bool
T_23: (in fn4AC0 @ 07A7 : ptr16)
  Class: Eq_23
  DataType: (ptr16 Eq_23)
  OrigDataType: (ptr16 (fn T_25 ()))
T_24: (in signature of fn4AC0 : void)
  Class: Eq_24
  DataType: Eq_24
  OrigDataType: 
T_25: (in fn4AC0() @ 07A7 : void)
  Class: Eq_25
  DataType: void
  OrigDataType: void
*/
typedef struct Globals {
} Eq_1;

typedef struct Eq_2 {
	byte b001D;	// 1D
	byte b0157;	// 157
	bcu8 b80EA;	// 80EA
} Eq_2;

typedef void (Eq_7)();

typedef void (Eq_23)();

